
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author je_mg
 */
public class EmpaqueActualizayactiva extends javax.swing.JFrame {
Conexion con;
EmpaqueOperaciones em=new EmpaqueOperaciones();

String Username;


    /**
     * Creates new form Empaque
     */
    public EmpaqueActualizayactiva() {
        initComponents();
           setIconImage(new ImageIcon(getClass().getResource("/iconoSW/agro.jpg")).getImage());
          this.setLocationRelativeTo(null);
            
        btnaction2.setEnabled(false);
         CantidadActualizar.setEnabled(false);
    try {
        con.abreConexion();
            em.consultaTodosEmpaque(tablaactualiza, con.abreConexion());
        
       
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(EmpaqueOrigin.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel10 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Actualizaciones = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaactualiza = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        CantidadActualizar = new javax.swing.JTextField();
        btnaction2 = new javax.swing.JButton();
        actualiza = new javax.swing.JRadioButton();
        activa = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Minimiza = new javax.swing.JButton();
        regresa = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jTextField2.setText("jTextField1");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesLogin/fonodo.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Actualizaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaactualiza.setBackground(new java.awt.Color(102, 153, 255));
        tablaactualiza.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave del Empaque", "Nombre", "Capacidad", "Estatus", "Unidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaactualiza.setSelectionForeground(new java.awt.Color(153, 255, 153));
        jScrollPane4.setViewportView(tablaactualiza);

        Actualizaciones.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 530, 260));

        jPanel4.setLayout(null);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cantidad Nueva");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(10, 40, 96, 15);

        CantidadActualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CantidadActualizarKeyTyped(evt);
            }
        });
        jPanel4.add(CantidadActualizar);
        CantidadActualizar.setBounds(110, 30, 180, 30);

        btnaction2.setText("Action");
        btnaction2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaction2ActionPerformed(evt);
            }
        });
        jPanel4.add(btnaction2);
        btnaction2.setBounds(440, 60, 100, 23);

        actualiza.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(actualiza);
        actualiza.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        actualiza.setForeground(new java.awt.Color(255, 255, 255));
        actualiza.setText("Actualizar Campos");
        actualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizaActionPerformed(evt);
            }
        });
        jPanel4.add(actualiza);
        actualiza.setBounds(390, 30, 153, 25);

        activa.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(activa);
        activa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        activa.setForeground(new java.awt.Color(255, 255, 255));
        activa.setText("Activar");
        activa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activaActionPerformed(evt);
            }
        });
        jPanel4.add(activa);
        activa.setBounds(300, 30, 90, 23);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesLogin/fonodo.jpg"))); // NOI18N
        jPanel4.add(jLabel14);
        jLabel14.setBounds(0, 0, 560, 90);

        Actualizaciones.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 550, 90));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenpaquete/fondo-de-madera-realista_1022-69.jpg"))); // NOI18N
        Actualizaciones.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 570, 420));

        jTabbedPane1.addTab("Actualizaciones", Actualizaciones);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 570, 390));

        Minimiza.setText("-");
        Minimiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizaActionPerformed(evt);
            }
        });
        getContentPane().add(Minimiza, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 40, 20));
        Minimiza.getAccessibleContext().setAccessibleDescription("");

        regresa.setText("<");
        regresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresaActionPerformed(evt);
            }
        });
        getContentPane().add(regresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 40, 20));

        salir.setText("X");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 40, 20));
        salir.getAccessibleContext().setAccessibleDescription("");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesLogin/fonodo.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MinimizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizaActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MinimizaActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        con.cerrarConexion();
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed
public void borraT(JTable tbl){
DefaultTableModel tam=(DefaultTableModel)tbl.getModel();
    for (int i = tam.getRowCount()-1; i >=0; i--) {
        tam.removeRow(i);
        tam.removeTableModelListener(tbl);
    }
}
    private void regresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresaActionPerformed
         Menu m=new Menu();
           m.setVisible(true);
            m.usuario=String.valueOf(Username);
           
           dispose();
    }//GEN-LAST:event_regresaActionPerformed

    private void CantidadActualizarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CantidadActualizarKeyTyped
               char Validar=evt.getKeyChar();
      if(Character.isLetter(Validar)){
      getToolkit().beep();
      evt.consume();
          JOptionPane.showConfirmDialog(rootPane, "Ingrese solo numeros");
      }
    }//GEN-LAST:event_CantidadActualizarKeyTyped

    private void btnaction2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaction2ActionPerformed
 if(activa.isSelected()){
            Object dato[]=new Object[10];
            dato[0]="'A'";
            int a= tablaactualiza.getSelectedRow();
           if(a!=-1 ){
                 Object p;
                   p= String.valueOf(tablaactualiza.getValueAt(tablaactualiza.getSelectedRow(), 3).toString());

               if( p.equals("B")){
                
            
           dato[1]=Integer.parseInt(String.valueOf(tablaactualiza.getValueAt(tablaactualiza.getSelectedRow(), 0)));
          em.Activar(dato);
          
                   borraT(tablaactualiza);
            
            
              try {
       
                  em.consultaTodosEmpaque(tablaactualiza, con.abreConexion());
                  
              } catch (ClassNotFoundException ex) {
        
                  Logger.getLogger(EmpaqueOrigin.class.getName()).log(Level.SEVERE, null, ex);
    
                                                   }
               }else{ JOptionPane.showConfirmDialog(null, "Selecione un renglon de Baja");   }
             }else{
                          JOptionPane.showConfirmDialog(null, "Selecione un renglon");

           }
              CantidadActualizar.setText(null);
     
       
      
     }else if(actualiza.isSelected()){
        Object dato[]=new Object[10];
        
            int a= tablaactualiza.getSelectedRow();
           if(a!=-1 ){
               

               if(!CantidadActualizar.getText().isEmpty()){
                    dato[0]=Integer.parseInt(String.valueOf(CantidadActualizar.getText().toString()));
            
           dato[1]=Integer.parseInt(String.valueOf(tablaactualiza.getValueAt(tablaactualiza.getSelectedRow(), 0)));
          em.actualizarCantidad(dato);
       
                   borraT(tablaactualiza);
           
            
              try {
       
                  em.consultaTodosEmpaque(tablaactualiza, con.abreConexion());
                    
              } catch (ClassNotFoundException ex) {
        
                  Logger.getLogger(EmpaqueOrigin.class.getName()).log(Level.SEVERE, null, ex);
    
                                                   }
               }else{ JOptionPane.showMessageDialog(null, "ingrese un valor");   }
             }else{
                          JOptionPane.showMessageDialog(null, "selecione un renglon");}
   CantidadActualizar.setText(null);
        
           }
           
    }//GEN-LAST:event_btnaction2ActionPerformed

    private void actualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizaActionPerformed
      btnaction2.setText(actualiza.getText());
    
        btnaction2.setEnabled(true);
      
      CantidadActualizar.setEnabled(true);
   // TODO add your handling code here:
    }//GEN-LAST:event_actualizaActionPerformed

    private void activaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activaActionPerformed
       btnaction2.setText(activa.getText());
   
        btnaction2.setEnabled(true);
    
      CantidadActualizar.setEnabled(false);

    }//GEN-LAST:event_activaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpaqueOrigin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpaqueOrigin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpaqueOrigin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpaqueOrigin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpaqueOrigin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Actualizaciones;
    private javax.swing.JTextField CantidadActualizar;
    private javax.swing.JButton Minimiza;
    private javax.swing.JRadioButton activa;
    private javax.swing.JRadioButton actualiza;
    private javax.swing.JButton btnaction2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton regresa;
    private javax.swing.JButton salir;
    private javax.swing.JTable tablaactualiza;
    // End of variables declaration//GEN-END:variables
}
