
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author je_mg
 */
public class EmpaqueConsultaBaja extends javax.swing.JFrame {
Conexion con;
EmpaqueOperaciones em=new EmpaqueOperaciones();

String Username;


    /**
     * Creates new form Empaque
     */
    public EmpaqueConsultaBaja() {
        initComponents();
           setIconImage(new ImageIcon(getClass().getResource("/iconoSW/agro.jpg")).getImage());
          this.setLocationRelativeTo(null);
       
       btnaction1.setEnabled(false);
      
       nombre1.setEnabled(false);
     
    try {
        con.abreConexion();
       
        em.consultaTodosEmpaque(tablaconsultaybaja, con.abreConexion());
        
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(EmpaqueOrigin.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel10 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        consultageneral = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaconsultaybaja = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        nombre1 = new javax.swing.JTextField();
        btnaction1 = new javax.swing.JButton();
        eliminar1 = new javax.swing.JRadioButton();
        consulta = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Minimiza = new javax.swing.JButton();
        regresa = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jTextField2.setText("jTextField1");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesLogin/fonodo.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        consultageneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaconsultaybaja.setBackground(new java.awt.Color(102, 153, 255));
        tablaconsultaybaja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave del Empaque", "Nombre", "Capacidad", "Estatus", "Unidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaconsultaybaja.setSelectionForeground(new java.awt.Color(153, 255, 153));
        jScrollPane1.setViewportView(tablaconsultaybaja);

        consultageneral.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 530, 260));

        jPanel3.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nombre");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(0, 20, 47, 15);

        nombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombre1KeyTyped(evt);
            }
        });
        jPanel3.add(nombre1);
        nombre1.setBounds(60, 10, 180, 30);

        btnaction1.setText("Action");
        btnaction1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaction1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnaction1);
        btnaction1.setBounds(360, 30, 100, 23);

        eliminar1.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(eliminar1);
        eliminar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        eliminar1.setForeground(new java.awt.Color(255, 255, 255));
        eliminar1.setText("Eliminar");
        eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar1ActionPerformed(evt);
            }
        });
        jPanel3.add(eliminar1);
        eliminar1.setBounds(260, 10, 79, 25);

        consulta.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(consulta);
        consulta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        consulta.setForeground(new java.awt.Color(255, 255, 255));
        consulta.setText("Consulta");
        consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaActionPerformed(evt);
            }
        });
        jPanel3.add(consulta);
        consulta.setBounds(260, 50, 90, 23);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesLogin/fonodo.jpg"))); // NOI18N
        jPanel3.add(jLabel12);
        jLabel12.setBounds(-10, 0, 480, 90);

        consultageneral.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 470, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenpaquete/fondo-de-madera-realista_1022-69.jpg"))); // NOI18N
        consultageneral.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 570, 420));

        jTabbedPane1.addTab("Bajas y Consultas", consultageneral);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 570, 390));

        Minimiza.setText("-");
        Minimiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizaActionPerformed(evt);
            }
        });
        getContentPane().add(Minimiza, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 40, 20));
        Minimiza.getAccessibleContext().setAccessibleDescription("");

        regresa.setText("<");
        regresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresaActionPerformed(evt);
            }
        });
        getContentPane().add(regresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 40, 20));

        salir.setText("X");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 40, 20));
        salir.getAccessibleContext().setAccessibleDescription("");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesLogin/fonodo.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MinimizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizaActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MinimizaActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        con.cerrarConexion();
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed
public void borraT(){
DefaultTableModel tam=(DefaultTableModel)tablaconsultaybaja.getModel();
    for (int i = tam.getRowCount()-1; i >=0; i--) {
        tam.removeRow(i);
        tam.removeTableModelListener(tablaconsultaybaja);
    }
}
    private void regresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresaActionPerformed
         Menu m=new Menu();
           m.setVisible(true);
            m.usuario=String.valueOf(Username);
           
           dispose();
    }//GEN-LAST:event_regresaActionPerformed

    private void consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaActionPerformed

       
        btnaction1.setText(consulta.getText());

        btnaction1.setEnabled(true);
      
        nombre1.setEnabled(true);
       
    }//GEN-LAST:event_consultaActionPerformed

    private void eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar1ActionPerformed
      
        btnaction1.setText(eliminar1.getText());
  
        btnaction1.setEnabled(true);
      

        nombre1.setEnabled(false);
    }//GEN-LAST:event_eliminar1ActionPerformed

    private void btnaction1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaction1ActionPerformed
        if(consulta.isSelected()){
            if(!nombre1.getText().isEmpty()){
                Object dato[]=new Object[10];

                dato[0]=String.valueOf(nombre1.getText());
                try {
                    borraT();
                    em.consultaEspecifica(tablaconsultaybaja, con.abreConexion(), dato);
                    this.repaint();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(EmpaqueOrigin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                JOptionPane.showConfirmDialog(null, "Minimo ingresa Clave y nombre");
            }

           

            nombre1.setText(null);
        }else if(eliminar1.isSelected()){
            Object dato[]=new Object[10];
            dato[0]="'B'";
            int a= tablaconsultaybaja.getSelectedRow();

            if(a!=-1 ){
                Object p;
                p= String.valueOf(tablaconsultaybaja.getValueAt(tablaconsultaybaja.getSelectedRow(), 3).toString());

                if( p.equals("A")){
                    dato[1]=Integer.parseInt(String.valueOf(tablaconsultaybaja.getValueAt(tablaconsultaybaja.getSelectedRow(), 0)));
                    em.BajaEmpaque(dato);
                    
                    borraT();
                

                    try {

                        em.consultaTodosEmpaque(tablaconsultaybaja, con.abreConexion());

                  
                    } catch (ClassNotFoundException ex) {

                        Logger.getLogger(EmpaqueOrigin.class.getName()).log(Level.SEVERE, null, ex);

                    }
                }else{ JOptionPane.showConfirmDialog(null, "Selecione un renglon de Alta");   }
            }else{
                JOptionPane.showConfirmDialog(null, "Seleccione un renglon");

            }

          

            nombre1.setText(null);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaction1ActionPerformed

    private void nombre1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpaqueOrigin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpaqueOrigin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpaqueOrigin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpaqueOrigin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpaqueOrigin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Minimiza;
    private javax.swing.JButton btnaction1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton consulta;
    private javax.swing.JPanel consultageneral;
    private javax.swing.JRadioButton eliminar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField nombre1;
    private javax.swing.JButton regresa;
    private javax.swing.JButton salir;
    private javax.swing.JTable tablaconsultaybaja;
    // End of variables declaration//GEN-END:variables
}
