
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author je_mg
 */
public class EmpaqueOrigin extends javax.swing.JFrame {
Conexion con;
EmpaqueOperaciones em=new EmpaqueOperaciones();

String Username;


    /**
     * Creates new form Empaque
     */
    public EmpaqueOrigin() {
        initComponents();
           setIconImage(new ImageIcon(getClass().getResource("/iconoSW/agro.jpg")).getImage());
          this.setLocationRelativeTo(null);
             Clave.setEnabled(false);
       nombre.setEnabled(false);
       Cantidad.setEnabled(false);
       MEDIDAUNI.setEnabled(false);
       btnaction1.setEnabled(false);
        btnaction.setEnabled(false);
       nombre1.setEnabled(false);
        btnaction2.setEnabled(false);
         CantidadActualizar.setEnabled(false);
    try {
        con.abreConexion();
        em.consultaregistroE(MEDIDAUNI, con.abreConexion());
        em.consultaTodosEmpaque(tablaconsultaybaja, con.abreConexion());
          em.consultaTodosEmpaque(tablaactualiza, con.abreConexion());
         em.consultaTodosEmpaque(tablageneral, con.abreConexion());
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(EmpaqueOrigin.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel10 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        consultageneral = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaconsultaybaja = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        nombre1 = new javax.swing.JTextField();
        btnaction1 = new javax.swing.JButton();
        eliminar1 = new javax.swing.JRadioButton();
        consulta = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        registro = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MEDIDAUNI = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        Clave = new javax.swing.JTextField();
        Cantidad = new javax.swing.JTextField();
        registrar = new javax.swing.JRadioButton();
        btnaction = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        consultayelimina = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablageneral = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        Actualizaciones = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaactualiza = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        CantidadActualizar = new javax.swing.JTextField();
        btnaction2 = new javax.swing.JButton();
        actualiza = new javax.swing.JRadioButton();
        activa = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Minimiza = new javax.swing.JButton();
        regresa = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jTextField2.setText("jTextField1");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesLogin/fonodo.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        consultageneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaconsultaybaja.setBackground(new java.awt.Color(102, 153, 255));
        tablaconsultaybaja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave del Empaque", "Nombre", "Capacidad", "Estatus", "Unidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaconsultaybaja.setSelectionForeground(new java.awt.Color(153, 255, 153));
        jScrollPane1.setViewportView(tablaconsultaybaja);

        consultageneral.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 530, 260));

        jPanel3.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nombre");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(0, 20, 47, 15);

        nombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombre1KeyTyped(evt);
            }
        });
        jPanel3.add(nombre1);
        nombre1.setBounds(60, 10, 180, 30);

        btnaction1.setText("Action");
        btnaction1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaction1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnaction1);
        btnaction1.setBounds(300, 50, 100, 23);

        eliminar1.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(eliminar1);
        eliminar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        eliminar1.setForeground(new java.awt.Color(255, 255, 255));
        eliminar1.setText("Eliminar");
        eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar1ActionPerformed(evt);
            }
        });
        jPanel3.add(eliminar1);
        eliminar1.setBounds(360, 10, 79, 25);

        consulta.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(consulta);
        consulta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        consulta.setForeground(new java.awt.Color(255, 255, 255));
        consulta.setText("Consulta");
        consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaActionPerformed(evt);
            }
        });
        jPanel3.add(consulta);
        consulta.setBounds(250, 10, 90, 23);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesLogin/fonodo.jpg"))); // NOI18N
        jPanel3.add(jLabel12);
        jLabel12.setBounds(-10, 0, 480, 90);

        consultageneral.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 470, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenpaquete/fondo-de-madera-realista_1022-69.jpg"))); // NOI18N
        consultageneral.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 570, 420));

        jTabbedPane1.addTab("Bajas y Consultas", consultageneral);

        registro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MEDIDAUNI.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(MEDIDAUNI);

        registro.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 390, 90));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre");
        registro.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cantidad");
        registro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Unidad de Medida");
        registro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Clave");
        registro.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreKeyTyped(evt);
            }
        });
        registro.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 180, -1));

        Clave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ClaveKeyTyped(evt);
            }
        });
        registro.add(Clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 180, -1));

        Cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CantidadKeyTyped(evt);
            }
        });
        registro.add(Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 180, -1));

        registrar.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(registrar);
        registrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        registrar.setForeground(new java.awt.Color(255, 255, 255));
        registrar.setText("Registrar");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        registro.add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 110, -1));

        btnaction.setText("Action");
        btnaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactionActionPerformed(evt);
            }
        });
        registro.add(btnaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenpaquete/fondo-de-madera-realista_1022-69.jpg"))); // NOI18N
        registro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 400));

        jTabbedPane1.addTab("Registro", registro);

        consultayelimina.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablageneral.setBackground(new java.awt.Color(102, 153, 255));
        tablageneral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave del Empaque", "Nombre", "Capacidad", "Estatus", "Unidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablageneral.setSelectionForeground(new java.awt.Color(153, 255, 153));
        jScrollPane3.setViewportView(tablageneral);

        consultayelimina.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 540, 330));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenpaquete/fondo-de-madera-realista_1022-69.jpg"))); // NOI18N
        consultayelimina.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 570, 420));

        jTabbedPane1.addTab("Lista General", consultayelimina);

        Actualizaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaactualiza.setBackground(new java.awt.Color(102, 153, 255));
        tablaactualiza.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave del Empaque", "Nombre", "Capacidad", "Estatus", "Unidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaactualiza.setSelectionForeground(new java.awt.Color(153, 255, 153));
        jScrollPane4.setViewportView(tablaactualiza);

        Actualizaciones.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 530, 260));

        jPanel4.setLayout(null);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cantidad Nueva");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(10, 40, 96, 15);

        CantidadActualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CantidadActualizarKeyTyped(evt);
            }
        });
        jPanel4.add(CantidadActualizar);
        CantidadActualizar.setBounds(110, 30, 180, 30);

        btnaction2.setText("Action");
        btnaction2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaction2ActionPerformed(evt);
            }
        });
        jPanel4.add(btnaction2);
        btnaction2.setBounds(440, 60, 100, 23);

        actualiza.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(actualiza);
        actualiza.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        actualiza.setForeground(new java.awt.Color(255, 255, 255));
        actualiza.setText("Actualizar Campos");
        actualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizaActionPerformed(evt);
            }
        });
        jPanel4.add(actualiza);
        actualiza.setBounds(390, 30, 153, 25);

        activa.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(activa);
        activa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        activa.setForeground(new java.awt.Color(255, 255, 255));
        activa.setText("Activar");
        activa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activaActionPerformed(evt);
            }
        });
        jPanel4.add(activa);
        activa.setBounds(300, 30, 90, 23);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesLogin/fonodo.jpg"))); // NOI18N
        jPanel4.add(jLabel14);
        jLabel14.setBounds(0, 0, 560, 90);

        Actualizaciones.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 550, 90));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenpaquete/fondo-de-madera-realista_1022-69.jpg"))); // NOI18N
        Actualizaciones.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 570, 420));

        jTabbedPane1.addTab("Actualiza Cantidad", Actualizaciones);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 570, 390));

        Minimiza.setText("-");
        Minimiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizaActionPerformed(evt);
            }
        });
        getContentPane().add(Minimiza, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 40, 20));
        Minimiza.getAccessibleContext().setAccessibleDescription("");

        regresa.setText("<");
        regresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresaActionPerformed(evt);
            }
        });
        getContentPane().add(regresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 40, 20));

        salir.setText("X");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 40, 20));
        salir.getAccessibleContext().setAccessibleDescription("");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesLogin/fonodo.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MinimizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizaActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MinimizaActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        con.cerrarConexion();
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void ClaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ClaveKeyTyped
      char Validar=evt.getKeyChar();
      if(Character.isLetter(Validar)){
      getToolkit().beep();
      evt.consume();
          JOptionPane.showConfirmDialog(rootPane, "Ingrese solo numeros");
      }
    }//GEN-LAST:event_ClaveKeyTyped

    private void nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyTyped
       
    }//GEN-LAST:event_nombreKeyTyped

    private void CantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CantidadKeyTyped
        char Validar=evt.getKeyChar();
      if(Character.isLetter(Validar)){
      getToolkit().beep();
      evt.consume();
          JOptionPane.showConfirmDialog(rootPane, "Ingrese solo numeros");
      }
    }//GEN-LAST:event_CantidadKeyTyped

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
      CantidadActualizar.setEnabled(false);
    
        btnaction.setText(registrar.getText());
    btnaction1.setText("Action");
      btnaction2.setText("Action");
       nombre1.setEnabled(false);
       btnaction1.setEnabled(false);
        btnaction2.setEnabled(false);
        btnaction.setEnabled(true);
       Clave.setEnabled(true);
       nombre.setEnabled(true);
       Cantidad.setEnabled(true);
       MEDIDAUNI.setEnabled(true);
    }//GEN-LAST:event_registrarActionPerformed

    private void btnactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactionActionPerformed
       if(registrar.isSelected()){
             if(!Clave.getText().isEmpty() && !nombre.getText().isEmpty()){
           Object dato[]=new Object[10];
           dato[0]=Integer.parseInt(String.valueOf(Clave.getText()));
           dato[1]=String.valueOf(nombre.getText());
           dato[2]=Integer.parseInt(String.valueOf(Cantidad.getText()));
           dato[3]="'A'";
           dato[4]=Integer.parseInt(String.valueOf(MEDIDAUNI.getValueAt(MEDIDAUNI.getSelectedRow(), 0)));
          
           em.insertaEmpaque(dato);
              borraT(tablaconsultaybaja);
         borraT(tablaactualiza);
              borraT(tablageneral);
            
              try {
       
                  em.consultaTodosEmpaque(tablaconsultaybaja, con.abreConexion());
        
                  em.consultaTodosEmpaque(tablageneral, con.abreConexion());
    
                   em.consultaTodosEmpaque(tablaactualiza, con.abreConexion());
              } catch (ClassNotFoundException ex) {
        
                  Logger.getLogger(EmpaqueOrigin.class.getName()).log(Level.SEVERE, null, ex);
    
              }
       
            }else{
                 JOptionPane.showConfirmDialog(null, "Minimo ingresa Clave y nombre");
            } 
          CantidadActualizar.setText(null);
       Clave.setText(null);
       nombre.setText(null);
       Cantidad.setText(null);
       
    
       nombre1.setText(null);   
       }
    }//GEN-LAST:event_btnactionActionPerformed

    private void eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar1ActionPerformed
 btnaction.setEnabled(false);
        CantidadActualizar.setEnabled(false);
      btnaction2.setText("Action");    
    btnaction1.setText(eliminar1.getText());
          btnaction.setText("Action");
         btnaction1.setEnabled(true);
        btnaction.setEnabled(false);
       Clave.setEnabled(false);
       nombre.setEnabled(false);
       Cantidad.setEnabled(false);
       MEDIDAUNI.setEnabled(false);
     
       nombre1.setEnabled(false);
    }//GEN-LAST:event_eliminar1ActionPerformed

    private void btnaction1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaction1ActionPerformed
  if(consulta.isSelected()){
       if(!nombre1.getText().isEmpty()){
           Object dato[]=new Object[10];
        
           dato[0]=String.valueOf(nombre1.getText());
               try {
                   borraT(tablaconsultaybaja);
                   em.consultaEspecifica(tablaconsultaybaja, con.abreConexion(), dato);
               } catch (ClassNotFoundException ex) {
                   Logger.getLogger(EmpaqueOrigin.class.getName()).log(Level.SEVERE, null, ex);
               }
           }else{
              JOptionPane.showConfirmDialog(null, "Minimo ingresa Clave y nombre");
       }
      
        CantidadActualizar.setText(null);
       Clave.setText(null);
       nombre.setText(null);
       Cantidad.setText(null);
  
       nombre1.setText(null);   
       }else if(eliminar1.isSelected()){
            Object dato[]=new Object[10];
            dato[0]="'B'";
            int a= tablaconsultaybaja.getSelectedRow();
          
            if(a!=-1 ){
                      Object p;
            p= String.valueOf(tablaconsultaybaja.getValueAt(tablaconsultaybaja.getSelectedRow(), 3).toString());
            
                    if( p.equals("A")){
           dato[1]=Integer.parseInt(String.valueOf(tablaconsultaybaja.getValueAt(tablaconsultaybaja.getSelectedRow(), 0)));
          em.BajaEmpaque(dato);
           borraT(tablaconsultaybaja);
         borraT(tablaactualiza);
              borraT(tablageneral);
            
              try {
       
                  em.consultaTodosEmpaque(tablaconsultaybaja, con.abreConexion());
        
                  em.consultaTodosEmpaque(tablageneral, con.abreConexion());
    
                   em.consultaTodosEmpaque(tablaactualiza, con.abreConexion());
              } catch (ClassNotFoundException ex) {
        
                  Logger.getLogger(EmpaqueOrigin.class.getName()).log(Level.SEVERE, null, ex);
    
              }
            }else{ JOptionPane.showConfirmDialog(null, "Selecione un renglon de Alta");   }
             }else{
                          JOptionPane.showConfirmDialog(null, "Selecione un renglon");

           }
           
              CantidadActualizar.setText(null);
       Clave.setText(null);
       nombre.setText(null);
       Cantidad.setText(null);
       
     
       nombre1.setText(null);   
     }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaction1ActionPerformed
public void borraT(JTable tbl){
DefaultTableModel tam=(DefaultTableModel)tbl.getModel();
    for (int i = tam.getRowCount()-1; i >=0; i--) {
        tam.removeRow(i);
        tam.removeTableModelListener(tbl);
    }
}
    private void nombre1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre1KeyTyped

    private void consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaActionPerformed

       CantidadActualizar.setEnabled(false);
      btnaction2.setText("Action");
        btnaction1.setText(consulta.getText());
          btnaction.setText("Action");
         btnaction1.setEnabled(true);
        btnaction.setEnabled(false);
       Clave.setEnabled(false);
       nombre.setEnabled(false);
       Cantidad.setEnabled(false);
       MEDIDAUNI.setEnabled(false);
       nombre1.setEnabled(true);
        btnaction2.setEnabled(false);
    }//GEN-LAST:event_consultaActionPerformed

    private void regresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresaActionPerformed
         Menu m=new Menu();
           m.setVisible(true);
            m.usuario=String.valueOf(Username);
           
           dispose();
    }//GEN-LAST:event_regresaActionPerformed

    private void CantidadActualizarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CantidadActualizarKeyTyped
               char Validar=evt.getKeyChar();
      if(Character.isLetter(Validar)){
      getToolkit().beep();
      evt.consume();
          JOptionPane.showConfirmDialog(rootPane, "Ingrese solo numeros");
      }
    }//GEN-LAST:event_CantidadActualizarKeyTyped

    private void btnaction2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaction2ActionPerformed
 if(activa.isSelected()){
            Object dato[]=new Object[10];
            dato[0]="'A'";
            int a= tablaactualiza.getSelectedRow();
           if(a!=-1 ){
                 Object p;
                   p= String.valueOf(tablaactualiza.getValueAt(tablaactualiza.getSelectedRow(), 3).toString());

               if( p.equals("B")){
                
            
           dato[1]=Integer.parseInt(String.valueOf(tablaactualiza.getValueAt(tablaactualiza.getSelectedRow(), 0)));
          em.Activar(dato);
           borraT(tablaconsultaybaja);
                   borraT(tablaactualiza);
              borraT(tablageneral);
            
              try {
       
                  em.consultaTodosEmpaque(tablaactualiza, con.abreConexion());
                      em.consultaTodosEmpaque(tablaconsultaybaja, con.abreConexion());
                  em.consultaTodosEmpaque(tablageneral, con.abreConexion());
    
              } catch (ClassNotFoundException ex) {
        
    
    
                                                   }
               }else{ JOptionPane.showConfirmDialog(null, "Selecione un renglon de Baja");   }
             }else{
                          JOptionPane.showConfirmDialog(null, "Selecione un renglon");

           }
              CantidadActualizar.setText(null);
       Clave.setText(null);
       nombre.setText(null);
       Cantidad.setText(null);
       
       nombre1.setText(null);   
     }else if(actualiza.isSelected()){
        Object dato[]=new Object[10];
        
            int a= tablaactualiza.getSelectedRow();
           if(a!=-1 ){
               

               if(!CantidadActualizar.getText().isEmpty()){
                    dato[0]=Integer.parseInt(String.valueOf(CantidadActualizar.getText().toString()));
            
           dato[1]=Integer.parseInt(String.valueOf(tablaactualiza.getValueAt(tablaactualiza.getSelectedRow(), 0)));
          em.actualizarCantidad(dato);
           borraT(tablaconsultaybaja);
                   borraT(tablaactualiza);
              borraT(tablageneral);
            
              try {
       
                  em.consultaTodosEmpaque(tablaactualiza, con.abreConexion());
                      em.consultaTodosEmpaque(tablaconsultaybaja, con.abreConexion());
                  em.consultaTodosEmpaque(tablageneral, con.abreConexion());
    
              } catch (ClassNotFoundException ex) {
        
                  Logger.getLogger(EmpaqueOrigin.class.getName()).log(Level.SEVERE, null, ex);
    
                                                   }
               }else{ JOptionPane.showMessageDialog(null, "ingrese un valor");   }
             }else{
                          JOptionPane.showMessageDialog(null, "selecione un renglon");}
   CantidadActualizar.setText(null);
       Clave.setText(null);
       nombre.setText(null);
       Cantidad.setText(null);
       
       nombre1.setText(null);   
           }
           
    }//GEN-LAST:event_btnaction2ActionPerformed

    private void actualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizaActionPerformed
      btnaction2.setText(actualiza.getText());
    btnaction1.setText("Action");
    btnaction.setText("Action");
       nombre1.setEnabled(false);
        btnaction2.setEnabled(true);
       btnaction1.setEnabled(false);
        btnaction.setEnabled(false);
       Clave.setEnabled(false);
       nombre.setEnabled(false);
       Cantidad.setEnabled(false);
       MEDIDAUNI.setEnabled(false);
      CantidadActualizar.setEnabled(true);
   // TODO add your handling code here:
    }//GEN-LAST:event_actualizaActionPerformed

    private void activaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activaActionPerformed
       btnaction2.setText(activa.getText());
    btnaction1.setText("Action");
    btnaction.setText("Action");
       nombre1.setEnabled(false);
        btnaction2.setEnabled(true);
       btnaction1.setEnabled(false);
        btnaction.setEnabled(false);
       Clave.setEnabled(false);
       nombre.setEnabled(false);
       Cantidad.setEnabled(false);
       MEDIDAUNI.setEnabled(false);
      CantidadActualizar.setEnabled(false);

    }//GEN-LAST:event_activaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpaqueOrigin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpaqueOrigin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpaqueOrigin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpaqueOrigin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpaqueOrigin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Actualizaciones;
    private javax.swing.JTextField Cantidad;
    private javax.swing.JTextField CantidadActualizar;
    private javax.swing.JTextField Clave;
    private javax.swing.JTable MEDIDAUNI;
    private javax.swing.JButton Minimiza;
    private javax.swing.JRadioButton activa;
    private javax.swing.JRadioButton actualiza;
    private javax.swing.JButton btnaction;
    private javax.swing.JButton btnaction1;
    private javax.swing.JButton btnaction2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton consulta;
    private javax.swing.JPanel consultageneral;
    private javax.swing.JPanel consultayelimina;
    private javax.swing.JRadioButton eliminar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField nombre1;
    private javax.swing.JRadioButton registrar;
    private javax.swing.JPanel registro;
    private javax.swing.JButton regresa;
    private javax.swing.JButton salir;
    private javax.swing.JTable tablaactualiza;
    private javax.swing.JTable tablaconsultaybaja;
    private javax.swing.JTable tablageneral;
    // End of variables declaration//GEN-END:variables
}
