
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gavil
 */
public class LabConsulta extends javax.swing.JFrame {
String Username;
String a,b,c,d;
Conexion cont;
LaboratorioOperaciones la=new LaboratorioOperaciones();
/**
     * Creates new form LabConsulta
     */

    public LabConsulta() {       
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/iconoSW/agro.jpg")).getImage());
          this.setLocationRelativeTo(null);
         
    try {
        cont.abreConexion();
        la.consultaTodosLaboratorios(TablaLaboratorios, cont.abreConexion());
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(EmpaqueOrigin.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txfNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaLaboratorios = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        Minimiza = new javax.swing.JButton();
        regresa = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 69, 30));

        txfNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 305, 30));

        TablaLaboratorios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TablaLaboratorios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Laboratorio", "Nombre", "Origen", "Estatus"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaLaboratorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaLaboratoriosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaLaboratorios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 465, 240));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, 31));

        Minimiza.setText("-");
        Minimiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizaActionPerformed(evt);
            }
        });
        getContentPane().add(Minimiza, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 40, 20));

        regresa.setText("<");
        regresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresaActionPerformed(evt);
            }
        });
        getContentPane().add(regresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 40, 20));

        salir.setText("X");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 40, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesLogin/background.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents
       public void borrarTabla(JTable tabla){
        DefaultTableModel tamblatem=(DefaultTableModel)tabla.getModel();
            for (int i = tamblatem.getRowCount()-1; i >=0; i--) {
                tamblatem.removeRow(i);
                tamblatem.removeTableModelListener(tabla);
            }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     if(!txfNombre.getText().isEmpty()){
                Object dat[]= new Object[100];
                dat[0]= txfNombre.getText();
                
                try{
                    borrarTabla(TablaLaboratorios);
                    la.consultaEspecifica(TablaLaboratorios,cont.abreConexion(), dat);
                
                }catch(Exception ex){
                    Logger.getLogger(EmpaqueOrigin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                JOptionPane.showConfirmDialog(null, "Debes ingresar el Nombre");
            }
            
     
     
     
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void MinimizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizaActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MinimizaActionPerformed

    private void regresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresaActionPerformed
        Menu m=new Menu();
        m.setVisible(true);
        m.usuario=Username;
        dispose();
    }//GEN-LAST:event_regresaActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        cont.cerrarConexion();
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void txfNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfNombreKeyTyped

   char Validar=evt.getKeyChar();
      if(Character.isDigit(Validar)){
      getToolkit().beep();
      evt.consume();
          JOptionPane.showMessageDialog(rootPane, "Ingrese solo letras");
      }

    }//GEN-LAST:event_txfNombreKeyTyped

    private void TablaLaboratoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaLaboratoriosMouseClicked
        a=(String) TablaLaboratorios.getValueAt(TablaLaboratorios.getSelectedRow(),0);
        b=(String) TablaLaboratorios.getValueAt(TablaLaboratorios.getSelectedRow(),1);
        c=(String) TablaLaboratorios.getValueAt(TablaLaboratorios.getSelectedRow(),2);
       
        
        LabActualizar ew= new LabActualizar();
        ew.Datos(a, b,c); 
        ew.setVisible(true);
        dispose();
        
        
        
        
        
    }//GEN-LAST:event_TablaLaboratoriosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LabConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LabConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LabConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LabConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LabConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Minimiza;
    private javax.swing.JTable TablaLaboratorios;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton regresa;
    private javax.swing.JButton salir;
    private javax.swing.JTextField txfNombre;
    // End of variables declaration//GEN-END:variables
}
