
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gavil
 */
public class LabEliminar extends javax.swing.JFrame {
    String Username;
    Conexion cont;
    LaboratorioOperaciones la= new LaboratorioOperaciones();

    /**
     * Creates new form Laboratorio
     */
    public LabEliminar() {
        initComponents();
        this.setLocationRelativeTo(null);
            try {
        cont.abreConexion();
        la.consultaTodosLaboratorios(TablaLaboratorios, cont.abreConexion());
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(EmpaqueOrigin.class.getName()).log(Level.SEVERE, null, ex);
    }

    }
           
          
           public void borrarTabla(JTable tabla){
        DefaultTableModel tamblatem=(DefaultTableModel)tabla.getModel();
            for (int i = tamblatem.getRowCount()-1; i >=0; i--) {
                tamblatem.removeRow(i);
                tamblatem.removeTableModelListener(tabla);
            }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txfNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaLaboratorios = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        Minimiza = new javax.swing.JButton();
        regresa = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txfNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 168, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 122, 30));

        TablaLaboratorios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TablaLaboratorios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Laboratorio", "Nombre", "Origen", "Estatus"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaLaboratorios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 465, 290));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        Minimiza.setText("-");
        Minimiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizaActionPerformed(evt);
            }
        });
        getContentPane().add(Minimiza, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 40, 20));

        regresa.setText("<");
        regresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresaActionPerformed(evt);
            }
        });
        getContentPane().add(regresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 40, 20));

        salir.setText("X");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 40, 20));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Activar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesLogin/background.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        cont.cerrarConexion();
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void regresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresaActionPerformed
        Menu m=new Menu();
        m.setVisible(true);

        dispose();
    }//GEN-LAST:event_regresaActionPerformed

    private void MinimizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizaActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MinimizaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Object dat[]= new Object[10];
        int valor= TablaLaboratorios.getSelectedRow();

        if (valor!=-1){
            txfNombre.setText(String.valueOf(TablaLaboratorios.getValueAt(TablaLaboratorios.getSelectedRow(), 1)).toString());
            Object status;
            status= String.valueOf(TablaLaboratorios.getValueAt(TablaLaboratorios.getSelectedRow(), 3).toString());

            if( status.equals("A")){
                dat[0]=String.valueOf(TablaLaboratorios.getValueAt(TablaLaboratorios.getSelectedRow(), 1).toString());

                try{

                    la.elimina(dat,cont.abreConexion());
                    borrarTabla(TablaLaboratorios);
                }catch(Exception ex){
                    Logger.getLogger(EmpaqueOrigin.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    la.consultaTodosLaboratorios(TablaLaboratorios, cont.abreConexion());
                    this.repaint();
                }catch (Exception ex) {
                    Logger.getLogger(EmpaqueOrigin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                JOptionPane.showMessageDialog(null,"Seleccione un registro con baja");
            }

        }else{
            JOptionPane.showMessageDialog(null,"Debe Seleccuonar una fila");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txfNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfNombreKeyTyped
   char Validar=evt.getKeyChar();
      if(Character.isDigit(Validar)){
      getToolkit().beep();
      evt.consume();
          JOptionPane.showMessageDialog(rootPane, "Ingrese solo letras");
      }
    }//GEN-LAST:event_txfNombreKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         
            Object dat[]= new Object[10];
        int valor= TablaLaboratorios.getSelectedRow();

        if (valor!=-1){
            txfNombre.setText(String.valueOf(TablaLaboratorios.getValueAt(TablaLaboratorios.getSelectedRow(), 1)).toString());
            Object status;
            status= String.valueOf(TablaLaboratorios.getValueAt(TablaLaboratorios.getSelectedRow(), 3).toString());

            if( status.equals("B")){
                dat[0]=String.valueOf(TablaLaboratorios.getValueAt(TablaLaboratorios.getSelectedRow(), 1).toString());

                try{

                    la.Activa(dat,cont.abreConexion());
                    borrarTabla(TablaLaboratorios);
                }catch(Exception ex){
                    Logger.getLogger(EmpaqueOrigin.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    la.consultaTodosLaboratorios(TablaLaboratorios, cont.abreConexion());
                    this.repaint();
                }catch (Exception ex) {
                    Logger.getLogger(EmpaqueOrigin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                JOptionPane.showMessageDialog(null,"Seleccione un registro con baja");
            }

        }else{
            JOptionPane.showMessageDialog(null,"Debe Seleccuonar una fila");
        }

   
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laboratorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Minimiza;
    private javax.swing.JTable TablaLaboratorios;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton regresa;
    private javax.swing.JButton salir;
    private javax.swing.JTextField txfNombre;
    // End of variables declaration//GEN-END:variables
}
